package main

import (
	"fmt"
	"math"
	"strings"
)

// ─── C Code Generator ─────────────────────────────────────────────────────────

type CGen struct {
	sb         strings.Builder
	indent     int
	structs    map[string]*StructDef
	functions  map[string]*FuncDef
	imports    map[string]bool
	varTypes   map[string]*Type // for tracking auto-types in current func
	scopeStack []map[string]*Type
	errors     []PycError
	file       string
}

func NewCGen(structs map[string]*StructDef, functions map[string]*FuncDef, file string) *CGen {
	return &CGen{
		structs:   structs,
		functions: functions,
		imports:   make(map[string]bool),
		file:      file,
	}
}

func (g *CGen) w(format string, args ...interface{}) {
	g.sb.WriteString(strings.Repeat("    ", g.indent))
	g.sb.WriteString(fmt.Sprintf(format, args...))
}

func (g *CGen) wl(format string, args ...interface{}) {
	g.w(format+"\n", args...)
}

func (g *CGen) wraw(s string) {
	g.sb.WriteString(s)
}

func (g *CGen) nl() {
	g.sb.WriteString("\n")
}

func (g *CGen) pushVarScope() {
	g.scopeStack = append(g.scopeStack, make(map[string]*Type))
}

func (g *CGen) popVarScope() {
	if len(g.scopeStack) > 0 {
		g.scopeStack = g.scopeStack[:len(g.scopeStack)-1]
	}
}

func (g *CGen) setVarType(name string, t *Type) {
	if len(g.scopeStack) > 0 {
		g.scopeStack[len(g.scopeStack)-1][name] = t
	}
}

func (g *CGen) lookupVarType(name string) *Type {
	for i := len(g.scopeStack) - 1; i >= 0; i-- {
		if t, ok := g.scopeStack[i][name]; ok {
			return t
		}
	}
	return nil
}

// ─── Type to C ────────────────────────────────────────────────────────────────

func (g *CGen) cType(t *Type) string {
	if t == nil { return "int" }
	switch t.Kind {
	case TyInt:
		return "long long"
	case TyFloat:
		return "double"
	case TyStr:
		return "char*"
	case TyBool:
		return "int"
	case TyVoid:
		return "void"
	case TyList:
		// We represent lists as PycList structs
		return "PycList*"
	case TyStruct:
		return t.Name + "*"
	case TyAny:
		return "void*"
	case TyNone:
		return "void*"
	}
	return "int"
}

func (g *CGen) cTypeDecl(t *Type, name string) string {
	return g.cType(t) + " " + name
}

// ─── Generate Full Program ───────────────────────────────────────────────────

func (g *CGen) Generate(prog *Program) string {
	// Collect imports
	for _, stmt := range prog.Stmts {
		if imp, ok := stmt.(*ImportStmt); ok {
			g.imports[imp.Module] = true
		}
	}

	var out strings.Builder

	// Standard headers
	out.WriteString("/* Generated by PyC transpiler */\n")
	out.WriteString("#include <stdio.h>\n")
	out.WriteString("#include <stdlib.h>\n")
	out.WriteString("#include <string.h>\n")
	out.WriteString("#include <math.h>\n")
	out.WriteString("#include <time.h>\n")
	out.WriteString("#include <ctype.h>\n")
	out.WriteString("\n")

	// Runtime
	out.WriteString(g.genRuntime())
	out.WriteString("\n")

	// Forward declare all structs
	for name := range g.structs {
		out.WriteString(fmt.Sprintf("typedef struct %s %s;\n", name, name))
	}
	if len(g.structs) > 0 { out.WriteString("\n") }

	// Struct definitions
	for _, sd := range g.structs {
		out.WriteString(g.genStruct(sd))
		out.WriteString("\n")
	}

	// Forward declare all user functions
	for _, fn := range g.functions {
		out.WriteString(g.genFuncProto(fn) + ";\n")
	}
	if len(g.functions) > 0 { out.WriteString("\n") }

	// Global statements (non-function, non-struct, non-import)
	g.indent = 0
	for _, stmt := range prog.Stmts {
		switch stmt.(type) {
		case *FuncDef, *StructDef, *ImportStmt:
			continue
		}
		g.genStmt(stmt)
	}
	globalCode := g.sb.String()
	g.sb.Reset()

	// Function definitions
	var funcCode strings.Builder
	for _, fn := range g.functions {
		// skip main — we'll generate it specially
		if fn.Name == "main" { continue }
		funcCode.WriteString(g.genFunc(fn))
		funcCode.WriteString("\n")
	}

	// Entry point
	mainCode := g.genMainWrapper(prog, globalCode)

	out.WriteString(funcCode.String())

	// Generate main function last
	if mainFn, ok := g.functions["main"]; ok {
		// user-defined main — wrap it
		out.WriteString(g.genFunc(mainFn))
		out.WriteString("\n")
	} else {
		out.WriteString(mainCode)
	}

	return out.String()
}

func (g *CGen) genMainWrapper(prog *Program, globalCode string) string {
	var sb strings.Builder
	sb.WriteString("int main(int argc, char** argv) {\n")
	sb.WriteString("    pyc_init();\n")
	if globalCode != "" {
		sb.WriteString(globalCode)
	}
	sb.WriteString("    return 0;\n")
	sb.WriteString("}\n")
	return sb.String()
}

// ─── Runtime Library ──────────────────────────────────────────────────────────

func (g *CGen) genRuntime() string {
	return `/* ── PyC Runtime ── */
#define PYC_TRUE  1
#define PYC_FALSE 0
#define PYC_NONE  NULL

/* Dynamic list (heap-allocated) */
typedef struct {
    void**  data;
    long long size;
    long long cap;
    int elem_size; /* 0 = pointer */
} PycList;

PycList* pyc_list_new(void) {
    PycList* l = (PycList*)malloc(sizeof(PycList));
    l->data = NULL; l->size = 0; l->cap = 0;
    return l;
}
void pyc_list_append(PycList* l, void* val) {
    if (l->size >= l->cap) {
        l->cap = l->cap == 0 ? 8 : l->cap * 2;
        l->data = (void**)realloc(l->data, sizeof(void*) * (size_t)l->cap);
    }
    l->data[l->size++] = val;
}
void* pyc_list_get(PycList* l, long long i) {
    if (i < 0) i += l->size;
    if (i < 0 || i >= l->size) { fprintf(stderr, "IndexError: list index %lld out of range (size %lld)\n", i, l->size); exit(1); }
    return l->data[i];
}
void pyc_list_set(PycList* l, long long i, void* val) {
    if (i < 0) i += l->size;
    if (i < 0 || i >= l->size) { fprintf(stderr, "IndexError: list index %lld out of range\n", i); exit(1); }
    l->data[i] = val;
}
void* pyc_list_pop(PycList* l, long long i) {
    if (i < 0) i += l->size;
    void* val = l->data[i];
    memmove(&l->data[i], &l->data[i+1], sizeof(void*) * (size_t)(l->size - i - 1));
    l->size--;
    return val;
}
long long pyc_list_len(PycList* l) { return l ? l->size : 0; }
void pyc_list_free(PycList* l) { if(l){ free(l->data); free(l); } }

/* String helpers */
char* pyc_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    memcpy(out, a, la); memcpy(out+la, b, lb); out[la+lb] = 0;
    return out;
}
int pyc_str_startswith(const char* s, const char* prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}
int pyc_str_endswith(const char* s, const char* suffix) {
    size_t sl = strlen(s), pl = strlen(suffix);
    return sl >= pl && strcmp(s + sl - pl, suffix) == 0;
}
int pyc_str_contains(const char* s, const char* sub) {
    return strstr(s, sub) != NULL;
}
long long pyc_str_indexof(const char* s, const char* sub) {
    const char* p = strstr(s, sub);
    return p ? (long long)(p - s) : -1;
}
char* pyc_str_upper(const char* s) {
    char* out = strdup(s);
    for (int i = 0; out[i]; i++) out[i] = (char)toupper((unsigned char)out[i]);
    return out;
}
char* pyc_str_lower(const char* s) {
    char* out = strdup(s);
    for (int i = 0; out[i]; i++) out[i] = (char)tolower((unsigned char)out[i]);
    return out;
}
char* pyc_str_strip(const char* s) {
    while (isspace((unsigned char)*s)) s++;
    if (*s == 0) return strdup("");
    const char* end = s + strlen(s) - 1;
    while (end > s && isspace((unsigned char)*end)) end--;
    size_t len = (size_t)(end - s + 1);
    char* out = (char*)malloc(len + 1);
    memcpy(out, s, len); out[len] = 0;
    return out;
}
char* pyc_str_replace(const char* s, const char* from, const char* to) {
    if (!strstr(s, from)) return strdup(s);
    size_t fl = strlen(from), tl = strlen(to);
    size_t count = 0;
    const char* p = s;
    while ((p = strstr(p, from))) { count++; p += fl; }
    size_t newlen = strlen(s) + count * (tl > fl ? tl - fl : 0) + 1;
    char* out = (char*)malloc(newlen);
    char* op = out; p = s;
    while (*p) {
        if (strncmp(p, from, fl) == 0) { memcpy(op, to, tl); op += tl; p += fl; }
        else *op++ = *p++;
    }
    *op = 0;
    return out;
}
PycList* pyc_str_split(const char* s, const char* delim) {
    PycList* l = pyc_list_new();
    char* copy = strdup(s);
    char* tok = strtok(copy, delim);
    while (tok) { pyc_list_append(l, strdup(tok)); tok = strtok(NULL, delim); }
    free(copy);
    return l;
}
char* pyc_str_join(PycList* parts, const char* sep) {
    if (!parts || parts->size == 0) return strdup("");
    size_t total = 0, sl = strlen(sep);
    for (long long i = 0; i < parts->size; i++) total += strlen((char*)parts->data[i]);
    total += sl * (size_t)(parts->size - 1) + 1;
    char* out = (char*)malloc(total);
    out[0] = 0;
    for (long long i = 0; i < parts->size; i++) {
        if (i > 0) strcat(out, sep);
        strcat(out, (char*)parts->data[i]);
    }
    return out;
}
long long pyc_str_count(const char* s, const char* sub) {
    long long n = 0; const char* p = s;
    size_t sl = strlen(sub);
    while ((p = strstr(p, sub))) { n++; p += sl; }
    return n;
}
int pyc_str_isdigit(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isdigit((unsigned char)*s)) return 0;
    return 1;
}
int pyc_str_isalpha(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isalpha((unsigned char)*s)) return 0;
    return 1;
}
int pyc_str_isspace(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isspace((unsigned char)*s)) return 0;
    return 1;
}

/* int_to_str, float_to_str */
char* pyc_int_to_str(long long n) {
    char buf[64]; snprintf(buf, sizeof(buf), "%lld", n); return strdup(buf);
}
char* pyc_float_to_str(double n) {
    char buf[64]; snprintf(buf, sizeof(buf), "%g", n); return strdup(buf);
}
char* pyc_bool_to_str(int b) { return b ? strdup("True") : strdup("False"); }
long long pyc_str_to_int(const char* s) {
    char* end; long long v = strtoll(s, &end, 0);
    if (*end) { fprintf(stderr, "ValueError: invalid int literal '%s'\n", s); exit(1); }
    return v;
}
double pyc_str_to_float(const char* s) {
    char* end; double v = strtod(s, &end);
    if (*end) { fprintf(stderr, "ValueError: invalid float literal '%s'\n", s); exit(1); }
    return v;
}

/* print helpers */
void pyc_print_int(long long v)   { printf("%lld", v); }
void pyc_print_float(double v)    { printf("%g", v); }
void pyc_print_str(const char* v) { printf("%s", v); }
void pyc_print_bool(int v)        { printf("%s", v ? "True" : "False"); }
void pyc_println(void)            { printf("\n"); }

/* assert */
void pyc_assert(int cond, const char* msg) {
    if (!cond) { fprintf(stderr, "AssertionError: %s\n", msg ? msg : ""); exit(1); }
}

/* range (returns PycList of ints as void* cast) */
PycList* pyc_range(long long start, long long stop, long long step) {
    PycList* l = pyc_list_new();
    if (step == 0) { fprintf(stderr, "ValueError: range step cannot be zero\n"); exit(1); }
    if (step > 0) { for (long long i = start; i < stop; i += step) pyc_list_append(l, (void*)(intptr_t)i); }
    else          { for (long long i = start; i > stop; i += step) pyc_list_append(l, (void*)(intptr_t)i); }
    return l;
}

/* init */
void pyc_init(void) { srand((unsigned)time(NULL)); }
/* ── End Runtime ── */
`
}

// ─── Struct ───────────────────────────────────────────────────────────────────

func (g *CGen) genStruct(sd *StructDef) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("struct %s {\n", sd.Name))
	for _, f := range sd.Fields {
		sb.WriteString(fmt.Sprintf("    %s;\n", g.cTypeDecl(f.Type, f.Name)))
	}
	sb.WriteString("};\n")
	return sb.String()
}

// ─── Function Proto ───────────────────────────────────────────────────────────

func (g *CGen) genFuncProto(fn *FuncDef) string {
	ret := g.cType(fn.ReturnType)
	var params []string
	for _, p := range fn.Params {
		params = append(params, g.cTypeDecl(p.Type, p.Name))
	}
	if fn.Name == "main" {
		return "int main(int argc, char** argv)"
	}
	return fmt.Sprintf("%s %s(%s)", ret, fn.Name, strings.Join(params, ", "))
}

// ─── Function Body ────────────────────────────────────────────────────────────

func (g *CGen) genFunc(fn *FuncDef) string {
	old := g.sb
	g.sb.Reset()
	g.pushVarScope()
	for _, p := range fn.Params {
		g.setVarType(p.Name, p.Type)
	}

	g.indent = 0
	proto := g.genFuncProto(fn)
	g.wraw(proto + " {\n")
	g.indent = 1
	if fn.Name == "main" {
		g.wl("pyc_init();")
	}
	for _, stmt := range fn.Body {
		g.genStmt(stmt)
	}
	if typesEqual(fn.ReturnType, TypVoid) {
		g.wl("return;")
	}
	g.indent = 0
	g.wraw("}\n")
	g.popVarScope()

	result := g.sb.String()
	g.sb = old
	return result
}

// ─── Statement Code Gen ───────────────────────────────────────────────────────

func (g *CGen) genStmt(node Node) {
	if node == nil { return }
	switch n := node.(type) {
	case *VarDecl:
		g.genVarDecl(n)
	case *AssignStmt:
		g.genAssign(n)
	case *ReturnStmt:
		g.genReturn(n)
	case *IfStmt:
		g.genIf(n)
	case *WhileStmt:
		g.genWhile(n)
	case *ForStmt:
		g.genFor(n)
	case *BreakStmt:
		g.wl("break;")
	case *ContinueStmt:
		g.wl("continue;")
	case *PassStmt:
		g.wl("/* pass */")
	case *ExprStmt:
		expr := g.genExpr(n.Expr)
		if expr != "" {
			g.wl("%s;", expr)
		}
	case *DeleteStmt:
		expr := g.genExpr(n.Target)
		g.wl("free(%s);", expr)
	case *GlobalStmt:
		g.wl("/* global %s */", strings.Join(n.Names, ", "))
	case *FuncDef:
		// nested function def — generate in place (C doesn't support this, but we emit a comment)
		g.wl("/* note: nested function %s not supported in C */", n.Name)
	case *ImportStmt:
		// handled at top level
	}
}

func (g *CGen) genVarDecl(n *VarDecl) {
	ct := g.cType(n.Type)
	if n.Value == nil {
		// zero-initialize
		switch n.Type.Kind {
		case TyStr:
			g.wl("%s %s = \"\";", ct, n.Name)
		case TyList:
			g.wl("%s %s = pyc_list_new();", ct, n.Name)
		case TyBool:
			g.wl("%s %s = 0;", ct, n.Name)
		case TyFloat:
			g.wl("%s %s = 0.0;", ct, n.Name)
		default:
			g.wl("%s %s = 0;", ct, n.Name)
		}
	} else {
		val := g.genExpr(n.Value)
		g.wl("%s %s = %s;", ct, n.Name, val)
	}
	g.setVarType(n.Name, n.Type)
}

func (g *CGen) genAssign(n *AssignStmt) {
	target := g.genExpr(n.Target)
	val := g.genExpr(n.Value)

	// Check if this is auto-declaration (first assignment)
	if id, ok := n.Target.(*Ident); ok {
		if g.lookupVarType(id.Name) == nil && n.Op == "=" {
			// infer type from value
			t := g.inferExprType(n.Value)
			ct := g.cType(t)
			g.setVarType(id.Name, t)
			g.wl("%s %s = %s;", ct, id.Name, val)
			return
		}
	}

	switch n.Op {
	case "=":
		g.wl("%s = %s;", target, val)
	case "+=":
		// string concat check
		if id, ok := n.Target.(*Ident); ok {
			if t := g.lookupVarType(id.Name); t != nil && t.Kind == TyStr {
				g.wl("%s = pyc_str_concat(%s, %s);", target, target, val)
				return
			}
		}
		g.wl("%s += %s;", target, val)
	case "-=":
		g.wl("%s -= %s;", target, val)
	case "*=":
		g.wl("%s *= %s;", target, val)
	case "/=":
		g.wl("%s /= %s;", target, val)
	default:
		g.wl("%s = %s;", target, val)
	}
}

func (g *CGen) genReturn(n *ReturnStmt) {
	if n.Value == nil {
		g.wl("return;")
		return
	}
	val := g.genExpr(n.Value)
	g.wl("return %s;", val)
}

func (g *CGen) genIf(n *IfStmt) {
	cond := g.genExpr(n.Cond)
	g.wl("if (%s) {", cond)
	g.indent++
	for _, s := range n.Then { g.genStmt(s) }
	g.indent--
	for _, elif := range n.Elifs {
		c := g.genExpr(elif.Cond)
		g.wl("} else if (%s) {", c)
		g.indent++
		for _, s := range elif.Body { g.genStmt(s) }
		g.indent--
	}
	if n.ElseBody != nil {
		g.wl("} else {")
		g.indent++
		for _, s := range n.ElseBody { g.genStmt(s) }
		g.indent--
	}
	g.wl("}")
}

func (g *CGen) genWhile(n *WhileStmt) {
	cond := g.genExpr(n.Cond)
	g.wl("while (%s) {", cond)
	g.indent++
	g.pushVarScope()
	for _, s := range n.Body { g.genStmt(s) }
	g.popVarScope()
	g.indent--
	g.wl("}")
}

func (g *CGen) genFor(n *ForStmt) {
	g.pushVarScope()
	iter := n.Iter

	// Range loop special case
	if call, ok := iter.(*CallExpr); ok {
		if id, ok := call.Func.(*Ident); ok && id.Name == "range" {
			g.genForRange(n, call)
			g.popVarScope()
			return
		}
	}

	// General list iteration
	iterExpr := g.genExpr(iter)
	tmpList := fmt.Sprintf("_pyc_list_%s", n.Var)
	tmpIdx  := fmt.Sprintf("_pyc_i_%s", n.Var)
	g.wl("PycList* %s = %s;", tmpList, iterExpr)
	g.wl("for (long long %s = 0; %s < pyc_list_len(%s); %s++) {", tmpIdx, tmpIdx, tmpList, tmpIdx)
	g.indent++

	varType := n.VarType
	if varType == nil { varType = TypAny }
	ct := g.cType(varType)
	if varType.Kind == TyInt {
		g.wl("%s %s = (long long)(intptr_t)pyc_list_get(%s, %s);", ct, n.Var, tmpList, tmpIdx)
	} else if varType.Kind == TyStr {
		g.wl("%s %s = (char*)pyc_list_get(%s, %s);", ct, n.Var, tmpList, tmpIdx)
	} else {
		g.wl("void* %s = pyc_list_get(%s, %s);", n.Var, tmpList, tmpIdx)
	}
	g.setVarType(n.Var, varType)
	for _, s := range n.Body { g.genStmt(s) }
	g.indent--
	g.wl("}")
	g.popVarScope()
}

func (g *CGen) genForRange(n *ForStmt, call *CallExpr) {
	var startExpr, stopExpr, stepExpr string
	switch len(call.Args) {
	case 1:
		startExpr = "0"
		stopExpr  = g.genExpr(call.Args[0])
		stepExpr  = "1"
	case 2:
		startExpr = g.genExpr(call.Args[0])
		stopExpr  = g.genExpr(call.Args[1])
		stepExpr  = "1"
	case 3:
		startExpr = g.genExpr(call.Args[0])
		stopExpr  = g.genExpr(call.Args[1])
		stepExpr  = g.genExpr(call.Args[2])
	default:
		startExpr = "0"; stopExpr = "0"; stepExpr = "1"
	}
	g.setVarType(n.Var, TypInt)
	g.wl("for (long long %s = %s; %s < %s; %s += %s) {",
		n.Var, startExpr, n.Var, stopExpr, n.Var, stepExpr)
	g.indent++
	for _, s := range n.Body { g.genStmt(s) }
	g.indent--
	g.wl("}")
}

// ─── Expression Code Gen ──────────────────────────────────────────────────────

func (g *CGen) genExpr(node Node) string {
	if node == nil { return "0" }
	switch n := node.(type) {
	case *IntLit:
		return fmt.Sprintf("%dLL", n.Value)
	case *FloatLit:
		if math.IsInf(n.Value, 0) {
			return "HUGE_VAL"
		}
		return fmt.Sprintf("%s", n.Raw)
	case *StringLit:
		return fmt.Sprintf("%q", n.Value)
	case *BoolLit:
		if n.Value { return "PYC_TRUE" }
		return "PYC_FALSE"
	case *NoneLit:
		return "PYC_NONE"
	case *Ident:
		return n.Name
	case *ListLit:
		return g.genListLit(n)
	case *BinOp:
		return g.genBinOp(n)
	case *UnaryOp:
		return g.genUnaryOp(n)
	case *CallExpr:
		return g.genCall(n)
	case *IndexExpr:
		return g.genIndex(n)
	case *SliceExpr:
		return g.genSlice(n)
	case *AttrExpr:
		return g.genAttr(n)
	case *TernaryExpr:
		cond := g.genExpr(n.Cond)
		then := g.genExpr(n.Then)
		els  := g.genExpr(n.Else)
		return fmt.Sprintf("(%s ? %s : %s)", cond, then, els)
	case *FStringExpr:
		return g.genFString(n)
	case *NewExpr:
		return g.genNew(n)
	}
	return "0"
}

func (g *CGen) genListLit(n *ListLit) string {
	tmp := fmt.Sprintf("_pyc_lit_%d", n.Line*100+n.Col)
	// We generate a compound statement via a helper trick using comma operator
	// Better: generate a temp var statement before, but for inline we'll use a function
	// Since C doesn't allow inline blocks in expressions easily, generate as a series of appends
	// Return a string that declares+fills the list
	// Inline trick: use a block expression (GCC extension) or pre-declare
	// We'll use a named temp variable approach via a small macro expansion
	parts := []string{fmt.Sprintf("({")}
	parts = append(parts, fmt.Sprintf("PycList* %s = pyc_list_new();", tmp))
	for _, elem := range n.Elems {
		ev := g.genExpr(elem)
		et := g.inferExprType(elem)
		if et != nil && et.Kind == TyInt {
			parts = append(parts, fmt.Sprintf("pyc_list_append(%s, (void*)(intptr_t)(%s));", tmp, ev))
		} else if et != nil && et.Kind == TyStr {
			parts = append(parts, fmt.Sprintf("pyc_list_append(%s, (void*)%s);", tmp, ev))
		} else {
			parts = append(parts, fmt.Sprintf("pyc_list_append(%s, (void*)(intptr_t)(%s));", tmp, ev))
		}
	}
	parts = append(parts, fmt.Sprintf("%s; })", tmp))
	return strings.Join(parts, " ")
}

func (g *CGen) genBinOp(n *BinOp) string {
	lt := g.inferExprType(n.Left)
	rt := g.inferExprType(n.Right)

	left  := g.genExpr(n.Left)
	right := g.genExpr(n.Right)

	// String concatenation
	if n.Op == "+" && lt != nil && lt.Kind == TyStr {
		return fmt.Sprintf("pyc_str_concat(%s, %s)", left, right)
	}

	// Power
	if n.Op == "**" {
		return fmt.Sprintf("pow((double)(%s), (double)(%s))", left, right)
	}

	// Floor division
	if n.Op == "FLOORDIV" {
		if lt != nil && lt.Kind == TyFloat || rt != nil && rt.Kind == TyFloat {
			return fmt.Sprintf("floor((double)(%s) / (double)(%s))", left, right)
		}
		return fmt.Sprintf("((%s) / (%s))", left, right)
	}

	// Regular division — always float
	if n.Op == "/" {
		return fmt.Sprintf("((double)(%s) / (double)(%s))", left, right)
	}

	// Logical
	if n.Op == "&&" || n.Op == "||" {
		return fmt.Sprintf("(%s %s %s)", left, n.Op, right)
	}

	return fmt.Sprintf("(%s %s %s)", left, n.Op, right)
}

func (g *CGen) genUnaryOp(n *UnaryOp) string {
	operand := g.genExpr(n.Operand)
	return fmt.Sprintf("(%s%s)", n.Op, operand)
}

func (g *CGen) genCall(n *CallExpr) string {
	// Attribute call  x.method(...)
	if attr, ok := n.Func.(*AttrExpr); ok {
		return g.genMethodCall(attr, n.Args)
	}

	// Named function
	if id, ok := n.Func.(*Ident); ok {
		return g.genNamedCall(id.Name, n.Args)
	}

	fnExpr := g.genExpr(n.Func)
	var args []string
	for _, a := range n.Args { args = append(args, g.genExpr(a)) }
	return fmt.Sprintf("%s(%s)", fnExpr, strings.Join(args, ", "))
}

func (g *CGen) genNamedCall(name string, args []Node) string {
	switch name {
	case "print":
		return g.genPrint(args, false)
	case "println":
		return g.genPrint(args, true)
	case "len":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			arg := g.genExpr(args[0])
			if t != nil && t.Kind == TyStr {
				return fmt.Sprintf("(long long)strlen(%s)", arg)
			}
			return fmt.Sprintf("pyc_list_len(%s)", arg)
		}
	case "int":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			arg := g.genExpr(args[0])
			if t != nil && t.Kind == TyStr {
				return fmt.Sprintf("pyc_str_to_int(%s)", arg)
			}
			if t != nil && t.Kind == TyFloat {
				return fmt.Sprintf("(long long)(%s)", arg)
			}
			return fmt.Sprintf("(long long)(%s)", arg)
		}
	case "float":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			arg := g.genExpr(args[0])
			if t != nil && t.Kind == TyStr {
				return fmt.Sprintf("pyc_str_to_float(%s)", arg)
			}
			return fmt.Sprintf("(double)(%s)", arg)
		}
	case "str":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			arg := g.genExpr(args[0])
			if t != nil {
				switch t.Kind {
				case TyInt:
					return fmt.Sprintf("pyc_int_to_str(%s)", arg)
				case TyFloat:
					return fmt.Sprintf("pyc_float_to_str(%s)", arg)
				case TyBool:
					return fmt.Sprintf("pyc_bool_to_str(%s)", arg)
				default:
					return arg
				}
			}
			return arg
		}
	case "bool":
		if len(args) == 1 {
			arg := g.genExpr(args[0])
			return fmt.Sprintf("((%s) != 0)", arg)
		}
	case "abs":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			arg := g.genExpr(args[0])
			if t != nil && t.Kind == TyInt {
				return fmt.Sprintf("llabs(%s)", arg)
			}
			return fmt.Sprintf("fabs(%s)", arg)
		}
	case "max":
		if len(args) == 2 {
			a, b := g.genExpr(args[0]), g.genExpr(args[1])
			return fmt.Sprintf("((%s) > (%s) ? (%s) : (%s))", a, b, a, b)
		}
	case "min":
		if len(args) == 2 {
			a, b := g.genExpr(args[0]), g.genExpr(args[1])
			return fmt.Sprintf("((%s) < (%s) ? (%s) : (%s))", a, b, a, b)
		}
	case "range":
		switch len(args) {
		case 1:
			stop := g.genExpr(args[0])
			return fmt.Sprintf("pyc_range(0LL, %s, 1LL)", stop)
		case 2:
			start, stop := g.genExpr(args[0]), g.genExpr(args[1])
			return fmt.Sprintf("pyc_range(%s, %s, 1LL)", start, stop)
		case 3:
			start, stop, step := g.genExpr(args[0]), g.genExpr(args[1]), g.genExpr(args[2])
			return fmt.Sprintf("pyc_range(%s, %s, %s)", start, stop, step)
		}
	case "input":
		if len(args) == 1 {
			prompt := g.genExpr(args[0])
			return fmt.Sprintf("({ printf(\"%%s\", %s); char _buf[1024]; fgets(_buf, sizeof(_buf), stdin); _buf[strcspn(_buf, \"\\n\")] = 0; strdup(_buf); })", prompt)
		}
		return "({ char _buf[1024]; fgets(_buf, sizeof(_buf), stdin); _buf[strcspn(_buf, \"\\n\")] = 0; strdup(_buf); })"
	case "ord":
		if len(args) == 1 {
			arg := g.genExpr(args[0])
			return fmt.Sprintf("((long long)(unsigned char)(%s)[0])", arg)
		}
	case "chr":
		if len(args) == 1 {
			arg := g.genExpr(args[0])
			return fmt.Sprintf("(char[]){(char)(%s), 0}", arg)
		}
	case "exit":
		if len(args) == 1 {
			arg := g.genExpr(args[0])
			return fmt.Sprintf("exit((int)(%s))", arg)
		}
		return "exit(0)"
	case "assert":
		if len(args) >= 1 {
			cond := g.genExpr(args[0])
			msg := `"assertion failed"`
			if len(args) >= 2 {
				msg = g.genExpr(args[1])
			}
			return fmt.Sprintf("pyc_assert(%s, %s)", cond, msg)
		}
	case "sqrt":
		if len(args) == 1 { return fmt.Sprintf("sqrt((double)%s)", g.genExpr(args[0])) }
	case "floor":
		if len(args) == 1 { return fmt.Sprintf("(long long)floor(%s)", g.genExpr(args[0])) }
	case "ceil":
		if len(args) == 1 { return fmt.Sprintf("(long long)ceil(%s)", g.genExpr(args[0])) }
	case "round":
		if len(args) == 1 { return fmt.Sprintf("round(%s)", g.genExpr(args[0])) }
	case "pow":
		if len(args) == 2 { return fmt.Sprintf("pow((double)%s, (double)%s)", g.genExpr(args[0]), g.genExpr(args[1])) }
	case "hex":
		if len(args) == 1 { return fmt.Sprintf("({char _hb[32]; snprintf(_hb,sizeof(_hb),\"0x%%llx\",(long long)%s); strdup(_hb);})", g.genExpr(args[0])) }
	case "append":
		if len(args) == 2 {
			lst := g.genExpr(args[0])
			val := g.genExpr(args[1])
			t := g.inferExprType(args[1])
			if t != nil && t.Kind == TyInt {
				return fmt.Sprintf("pyc_list_append(%s, (void*)(intptr_t)(%s))", lst, val)
			}
			return fmt.Sprintf("pyc_list_append(%s, (void*)%s)", lst, val)
		}
	case "contains":
		if len(args) == 2 {
			container := g.genExpr(args[0])
			item := g.genExpr(args[1])
			t := g.inferExprType(args[0])
			if t != nil && t.Kind == TyStr {
				return fmt.Sprintf("pyc_str_contains(%s, %s)", container, item)
			}
		}
	case "startswith":
		if len(args) == 2 {
			return fmt.Sprintf("pyc_str_startswith(%s, %s)", g.genExpr(args[0]), g.genExpr(args[1]))
		}
	case "endswith":
		if len(args) == 2 {
			return fmt.Sprintf("pyc_str_endswith(%s, %s)", g.genExpr(args[0]), g.genExpr(args[1]))
		}
	case "upper":
		if len(args) == 1 { return fmt.Sprintf("pyc_str_upper(%s)", g.genExpr(args[0])) }
	case "lower":
		if len(args) == 1 { return fmt.Sprintf("pyc_str_lower(%s)", g.genExpr(args[0])) }
	case "strip":
		if len(args) == 1 { return fmt.Sprintf("pyc_str_strip(%s)", g.genExpr(args[0])) }
	case "replace":
		if len(args) == 3 { return fmt.Sprintf("pyc_str_replace(%s, %s, %s)", g.genExpr(args[0]), g.genExpr(args[1]), g.genExpr(args[2])) }
	case "split":
		if len(args) == 2 { return fmt.Sprintf("pyc_str_split(%s, %s)", g.genExpr(args[0]), g.genExpr(args[1])) }
		if len(args) == 1 { return fmt.Sprintf("pyc_str_split(%s, \" \")", g.genExpr(args[0])) }
	case "join":
		if len(args) == 2 { return fmt.Sprintf("pyc_str_join(%s, %s)", g.genExpr(args[0]), g.genExpr(args[1])) }
	case "printf":
		var cargs []string
		for _, a := range args { cargs = append(cargs, g.genExpr(a)) }
		return fmt.Sprintf("printf(%s)", strings.Join(cargs, ", "))
	case "scanf":
		var cargs []string
		for _, a := range args { cargs = append(cargs, g.genExpr(a)) }
		return fmt.Sprintf("scanf(%s)", strings.Join(cargs, ", "))
	case "rand_int":
		if len(args) == 2 {
			lo, hi := g.genExpr(args[0]), g.genExpr(args[1])
			return fmt.Sprintf("((long long)(rand() %% (%s - %s + 1)) + %s)", hi, lo, lo)
		}
	case "rand_float":
		return "((double)rand() / (double)RAND_MAX)"
	case "type_of":
		if len(args) == 1 {
			t := g.inferExprType(args[0])
			if t != nil {
				return fmt.Sprintf("%q", t.String())
			}
			return `"unknown"`
		}
	case "sleep":
		if len(args) == 1 {
			arg := g.genExpr(args[0])
			return fmt.Sprintf("({ struct timespec _ts; _ts.tv_sec = (time_t)(%s); _ts.tv_nsec = (long)((%s - (long long)(%s)) * 1e9); nanosleep(&_ts, NULL); })", arg, arg, arg)
		}
	}

	// User function or unknown — pass through
	var cargs []string
	for _, a := range args { cargs = append(cargs, g.genExpr(a)) }
	return fmt.Sprintf("%s(%s)", name, strings.Join(cargs, ", "))
}

func (g *CGen) genPrint(args []Node, newline bool) string {
	if len(args) == 0 {
		if newline { return `printf("\n")` }
		return `printf("")`
	}
	var parts []string
	var fmtStr strings.Builder
	var fmtArgs []string

	for _, arg := range args {
		t := g.inferExprType(arg)
		switch {
		case t != nil && t.Kind == TyInt:
			fmtStr.WriteString("%lld")
		case t != nil && t.Kind == TyFloat:
			fmtStr.WriteString("%g")
		case t != nil && t.Kind == TyBool:
			fmtStr.WriteString("%s")
		case t != nil && t.Kind == TyStr:
			fmtStr.WriteString("%s")
		default:
			fmtStr.WriteString("%s")
		}
		fmtStr.WriteString(" ")
		v := g.genExpr(arg)
		if t != nil && t.Kind == TyBool {
			fmtArgs = append(fmtArgs, fmt.Sprintf("(%s ? \"True\" : \"False\")", v))
		} else {
			fmtArgs = append(fmtArgs, v)
		}
	}
	// trim trailing space, add newline
	fmt_s := strings.TrimRight(fmtStr.String(), " ")
	if newline {
		fmt_s += "\\n"
	}
	parts = append(parts, fmt.Sprintf("%q", fmt_s))
	parts = append(parts, fmtArgs...)
	return fmt.Sprintf("printf(%s)", strings.Join(parts, ", "))
}

func (g *CGen) genMethodCall(attr *AttrExpr, args []Node) string {
	obj := g.genExpr(attr.Obj)
	objType := g.inferExprType(attr.Obj)
	method := attr.Attr

	switch {
	case objType != nil && objType.Kind == TyStr:
		switch method {
		case "upper":     return fmt.Sprintf("pyc_str_upper(%s)", obj)
		case "lower":     return fmt.Sprintf("pyc_str_lower(%s)", obj)
		case "strip":     return fmt.Sprintf("pyc_str_strip(%s)", obj)
		case "lstrip":    return fmt.Sprintf("pyc_str_strip(%s)", obj) // approx
		case "rstrip":    return fmt.Sprintf("pyc_str_strip(%s)", obj) // approx
		case "replace":
			if len(args) == 2 {
				return fmt.Sprintf("pyc_str_replace(%s, %s, %s)", obj, g.genExpr(args[0]), g.genExpr(args[1]))
			}
		case "startswith":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_startswith(%s, %s)", obj, g.genExpr(args[0])) }
		case "endswith":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_endswith(%s, %s)", obj, g.genExpr(args[0])) }
		case "contains":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_contains(%s, %s)", obj, g.genExpr(args[0])) }
		case "find", "index_of":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_indexof(%s, %s)", obj, g.genExpr(args[0])) }
		case "split":
			delim := `" "`
			if len(args) == 1 { delim = g.genExpr(args[0]) }
			return fmt.Sprintf("pyc_str_split(%s, %s)", obj, delim)
		case "join":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_join(%s, %s)", g.genExpr(args[0]), obj) }
		case "count":
			if len(args) == 1 { return fmt.Sprintf("pyc_str_count(%s, %s)", obj, g.genExpr(args[0])) }
		case "isdigit":  return fmt.Sprintf("pyc_str_isdigit(%s)", obj)
		case "isalpha":  return fmt.Sprintf("pyc_str_isalpha(%s)", obj)
		case "isspace":  return fmt.Sprintf("pyc_str_isspace(%s)", obj)
		case "format":
			// Basic format: treat as printf
			var fa []string
			for _, a := range args { fa = append(fa, g.genExpr(a)) }
			fmtParts := []string{obj}
			fmtParts = append(fmtParts, fa...)
			return fmt.Sprintf("pyc_str_format(%s)", strings.Join(fmtParts, ", "))
		}
	case objType != nil && objType.Kind == TyList:
		switch method {
		case "append":
			if len(args) == 1 {
				val := g.genExpr(args[0])
				t := g.inferExprType(args[0])
				if t != nil && t.Kind == TyInt {
					return fmt.Sprintf("pyc_list_append(%s, (void*)(intptr_t)(%s))", obj, val)
				}
				return fmt.Sprintf("pyc_list_append(%s, (void*)%s)", obj, val)
			}
		case "pop":
			if len(args) == 0 { return fmt.Sprintf("pyc_list_pop(%s, %s->size-1)", obj, obj) }
			if len(args) == 1 { return fmt.Sprintf("pyc_list_pop(%s, %s)", obj, g.genExpr(args[0])) }
		case "len":  return fmt.Sprintf("pyc_list_len(%s)", obj)
		case "sort": return fmt.Sprintf("/* sort(%s) -- not implemented */0", obj)
		case "reverse": return fmt.Sprintf("/* reverse(%s) -- not implemented */0", obj)
		case "clear": return fmt.Sprintf("((%s)->size = 0)", obj)
		case "contains":
			if len(args) == 1 {
				// linear search
				val := g.genExpr(args[0])
				tmp := fmt.Sprintf("_found_%d", attr.Line)
				return fmt.Sprintf("({ int %s = 0; for(long long _ci=0;_ci<%s->size;_ci++) if((long long)(intptr_t)%s->data[_ci]==(long long)(intptr_t)(%s)){%s=1;break;} %s; })", tmp, obj, obj, val, tmp, tmp)
			}
		}
	case objType != nil && objType.Kind == TyStruct:
		// struct field access that looks like a method — just return field
		return fmt.Sprintf("%s->%s", obj, method)
	}

	// Fallback
	var cargs []string
	for _, a := range args { cargs = append(cargs, g.genExpr(a)) }
	if len(cargs) > 0 {
		return fmt.Sprintf("%s_%s(%s, %s)", objType.String(), method, obj, strings.Join(cargs, ", "))
	}
	return fmt.Sprintf("%s_%s(%s)", objType.String(), method, obj)
}

func (g *CGen) genIndex(n *IndexExpr) string {
	obj := g.genExpr(n.Obj)
	idx := g.genExpr(n.Index)
	t := g.inferExprType(n.Obj)
	if t != nil && t.Kind == TyStr {
		return fmt.Sprintf("(char[]){(%s)[%s], 0}", obj, idx)
	}
	if t != nil && t.Kind == TyList && t.ElemType != nil && t.ElemType.Kind == TyInt {
		return fmt.Sprintf("((long long)(intptr_t)pyc_list_get(%s, %s))", obj, idx)
	}
	if t != nil && t.Kind == TyList && t.ElemType != nil && t.ElemType.Kind == TyStr {
		return fmt.Sprintf("((char*)pyc_list_get(%s, %s))", obj, idx)
	}
	return fmt.Sprintf("pyc_list_get(%s, %s)", obj, idx)
}

func (g *CGen) genSlice(n *SliceExpr) string {
	// String slice
	obj := g.genExpr(n.Obj)
	t := g.inferExprType(n.Obj)
	if t != nil && t.Kind == TyStr {
		low := "0"
		high := fmt.Sprintf("(long long)strlen(%s)", obj)
		if n.Low  != nil { low  = g.genExpr(n.Low) }
		if n.High != nil { high = g.genExpr(n.High) }
		return fmt.Sprintf("({ long long _lo=%s,_hi=%s; size_t _len=(size_t)(_hi>_lo?_hi-_lo:0); char* _sl=(char*)malloc(_len+1); memcpy(_sl,%s+_lo,_len); _sl[_len]=0; _sl; })", low, high, obj)
	}
	// List slice — return new list
	low := "0"
	high := fmt.Sprintf("pyc_list_len(%s)", obj)
	if n.Low  != nil { low  = g.genExpr(n.Low) }
	if n.High != nil { high = g.genExpr(n.High) }
	return fmt.Sprintf("({ PycList* _src=%s; PycList* _sl=pyc_list_new(); for(long long _si=%s;_si<%s;_si++) pyc_list_append(_sl,pyc_list_get(_src,_si)); _sl; })", obj, low, high)
}

func (g *CGen) genAttr(n *AttrExpr) string {
	obj := g.genExpr(n.Obj)
	t := g.inferExprType(n.Obj)
	if t != nil && t.Kind == TyStr {
		// Treat as a no-arg method call
		return g.genMethodCall(n, nil)
	}
	if t != nil && t.Kind == TyStruct {
		return fmt.Sprintf("%s->%s", obj, n.Attr)
	}
	return fmt.Sprintf("%s.%s", obj, n.Attr)
}

func (g *CGen) genFString(n *FStringExpr) string {
	// Build using snprintf
	var fmtStr strings.Builder
	var fmtArgs []string
	for _, part := range n.Parts {
		if !part.IsExpr {
			fmtStr.WriteString(strings.ReplaceAll(part.Text, "%", "%%"))
		} else {
			t := g.inferExprType(part.Expr)
			switch {
			case t != nil && t.Kind == TyInt:
				fmtStr.WriteString("%lld")
			case t != nil && t.Kind == TyFloat:
				fmtStr.WriteString("%g")
			case t != nil && t.Kind == TyBool:
				fmtStr.WriteString("%s")
			default:
				fmtStr.WriteString("%s")
			}
			v := g.genExpr(part.Expr)
			if t != nil && t.Kind == TyBool {
				fmtArgs = append(fmtArgs, fmt.Sprintf("(%s ? \"True\" : \"False\")", v))
			} else {
				fmtArgs = append(fmtArgs, v)
			}
		}
	}
	fmtLit := fmt.Sprintf("%q", fmtStr.String())
	allArgs := append([]string{fmtLit}, fmtArgs...)
	return fmt.Sprintf("({ char _fs[4096]; snprintf(_fs,sizeof(_fs),%s); strdup(_fs); })", strings.Join(allArgs, ", "))
}

func (g *CGen) genNew(n *NewExpr) string {
	sd, ok := g.structs[n.TypeName]
	if !ok { return fmt.Sprintf("malloc(sizeof(%s))", n.TypeName) }
	tmp := fmt.Sprintf("_new_%s_%d", n.TypeName, n.Line)
	var parts []string
	parts = append(parts, fmt.Sprintf("%s* %s = (%s*)malloc(sizeof(%s));", n.TypeName, tmp, n.TypeName, n.TypeName))
	for i, f := range sd.Fields {
		if i < len(n.Args) {
			parts = append(parts, fmt.Sprintf("%s->%s = %s;", tmp, f.Name, g.genExpr(n.Args[i])))
		} else {
			parts = append(parts, fmt.Sprintf("%s->%s = 0;", tmp, f.Name))
		}
	}
	parts = append(parts, tmp+";")
	return fmt.Sprintf("({ %s })", strings.Join(parts, " "))
}

// ─── Type Inference (best-effort, for codegen) ────────────────────────────────

func (g *CGen) inferExprType(node Node) *Type {
	if node == nil { return TypAny }
	switch n := node.(type) {
	case *IntLit:    return TypInt
	case *FloatLit:  return TypFloat
	case *StringLit: return TypStr
	case *BoolLit:   return TypBool
	case *NoneLit:   return TypNone
	case *Ident:
		if t := g.lookupVarType(n.Name); t != nil { return t }
		if n.ResolvedType != nil { return n.ResolvedType }
		if sig, ok := builtins[n.Name]; ok { return sig.RetType }
		return TypAny
	case *BinOp:
		lt := g.inferExprType(n.Left)
		rt := g.inferExprType(n.Right)
		cmpOps := map[string]bool{"==":true,"!=":true,"<":true,">":true,"<=":true,">=":true,"&&":true,"||":true}
		if cmpOps[n.Op] { return TypBool }
		if n.Op == "**" { return TypFloat }
		if n.Op == "/" { return TypFloat }
		if n.Op == "+" && lt != nil && lt.Kind == TyStr { return TypStr }
		if lt != nil && lt.Kind == TyFloat { return TypFloat }
		if rt != nil && rt.Kind == TyFloat { return TypFloat }
		return TypInt
	case *UnaryOp:
		if n.Op == "!" { return TypBool }
		return g.inferExprType(n.Operand)
	case *ListLit:
		if len(n.Elems) > 0 { return ListType(g.inferExprType(n.Elems[0])) }
		return ListType(TypAny)
	case *FStringExpr: return TypStr
	case *TernaryExpr:
		return g.inferExprType(n.Then)
	case *CallExpr:
		if id, ok := n.Func.(*Ident); ok {
			if sig, ok := builtins[id.Name]; ok { return sig.RetType }
			if fn, ok := g.functions[id.Name]; ok { return fn.ReturnType }
		}
		return TypAny
	case *IndexExpr:
		t := g.inferExprType(n.Obj)
		if t != nil && t.Kind == TyList && t.ElemType != nil { return t.ElemType }
		if t != nil && t.Kind == TyStr { return TypStr }
		return TypAny
	case *AttrExpr:
		t := g.inferExprType(n.Obj)
		if t != nil && t.Kind == TyStr {
			if sig, ok := strMethods[n.Attr]; ok { return sig.RetType }
		}
		if t != nil && t.Kind == TyList {
			if sig, ok := listMethods[n.Attr]; ok { return sig.RetType }
		}
		if t != nil && t.Kind == TyStruct {
			if sd, ok := g.structs[t.Name]; ok {
				for _, f := range sd.Fields {
					if f.Name == n.Attr { return f.Type }
				}
			}
		}
		return TypAny
	case *NewExpr:
		return StructType(n.TypeName)
	}
	return TypAny
}
