/* Generated by PyC transpiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <ctype.h>

/* ── PyC Runtime ── */
#define PYC_TRUE  1
#define PYC_FALSE 0
#define PYC_NONE  NULL

/* Dynamic list (heap-allocated) */
typedef struct {
    void**  data;
    long long size;
    long long cap;
    int elem_size; /* 0 = pointer */
} PycList;

PycList* pyc_list_new(void) {
    PycList* l = (PycList*)malloc(sizeof(PycList));
    l->data = NULL; l->size = 0; l->cap = 0;
    return l;
}
void pyc_list_append(PycList* l, void* val) {
    if (l->size >= l->cap) {
        l->cap = l->cap == 0 ? 8 : l->cap * 2;
        l->data = (void**)realloc(l->data, sizeof(void*) * (size_t)l->cap);
    }
    l->data[l->size++] = val;
}
void* pyc_list_get(PycList* l, long long i) {
    if (i < 0) i += l->size;
    if (i < 0 || i >= l->size) { fprintf(stderr, "IndexError: list index %lld out of range (size %lld)\n", i, l->size); exit(1); }
    return l->data[i];
}
void pyc_list_set(PycList* l, long long i, void* val) {
    if (i < 0) i += l->size;
    if (i < 0 || i >= l->size) { fprintf(stderr, "IndexError: list index %lld out of range\n", i); exit(1); }
    l->data[i] = val;
}
void* pyc_list_pop(PycList* l, long long i) {
    if (i < 0) i += l->size;
    void* val = l->data[i];
    memmove(&l->data[i], &l->data[i+1], sizeof(void*) * (size_t)(l->size - i - 1));
    l->size--;
    return val;
}
long long pyc_list_len(PycList* l) { return l ? l->size : 0; }
void pyc_list_free(PycList* l) { if(l){ free(l->data); free(l); } }

/* String helpers */
char* pyc_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    memcpy(out, a, la); memcpy(out+la, b, lb); out[la+lb] = 0;
    return out;
}
int pyc_str_startswith(const char* s, const char* prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}
int pyc_str_endswith(const char* s, const char* suffix) {
    size_t sl = strlen(s), pl = strlen(suffix);
    return sl >= pl && strcmp(s + sl - pl, suffix) == 0;
}
int pyc_str_contains(const char* s, const char* sub) {
    return strstr(s, sub) != NULL;
}
long long pyc_str_indexof(const char* s, const char* sub) {
    const char* p = strstr(s, sub);
    return p ? (long long)(p - s) : -1;
}
char* pyc_str_upper(const char* s) {
    char* out = strdup(s);
    for (int i = 0; out[i]; i++) out[i] = (char)toupper((unsigned char)out[i]);
    return out;
}
char* pyc_str_lower(const char* s) {
    char* out = strdup(s);
    for (int i = 0; out[i]; i++) out[i] = (char)tolower((unsigned char)out[i]);
    return out;
}
char* pyc_str_strip(const char* s) {
    while (isspace((unsigned char)*s)) s++;
    if (*s == 0) return strdup("");
    const char* end = s + strlen(s) - 1;
    while (end > s && isspace((unsigned char)*end)) end--;
    size_t len = (size_t)(end - s + 1);
    char* out = (char*)malloc(len + 1);
    memcpy(out, s, len); out[len] = 0;
    return out;
}
char* pyc_str_replace(const char* s, const char* from, const char* to) {
    if (!strstr(s, from)) return strdup(s);
    size_t fl = strlen(from), tl = strlen(to);
    size_t count = 0;
    const char* p = s;
    while ((p = strstr(p, from))) { count++; p += fl; }
    size_t newlen = strlen(s) + count * (tl > fl ? tl - fl : 0) + 1;
    char* out = (char*)malloc(newlen);
    char* op = out; p = s;
    while (*p) {
        if (strncmp(p, from, fl) == 0) { memcpy(op, to, tl); op += tl; p += fl; }
        else *op++ = *p++;
    }
    *op = 0;
    return out;
}
PycList* pyc_str_split(const char* s, const char* delim) {
    PycList* l = pyc_list_new();
    char* copy = strdup(s);
    char* tok = strtok(copy, delim);
    while (tok) { pyc_list_append(l, strdup(tok)); tok = strtok(NULL, delim); }
    free(copy);
    return l;
}
char* pyc_str_join(PycList* parts, const char* sep) {
    if (!parts || parts->size == 0) return strdup("");
    size_t total = 0, sl = strlen(sep);
    for (long long i = 0; i < parts->size; i++) total += strlen((char*)parts->data[i]);
    total += sl * (size_t)(parts->size - 1) + 1;
    char* out = (char*)malloc(total);
    out[0] = 0;
    for (long long i = 0; i < parts->size; i++) {
        if (i > 0) strcat(out, sep);
        strcat(out, (char*)parts->data[i]);
    }
    return out;
}
long long pyc_str_count(const char* s, const char* sub) {
    long long n = 0; const char* p = s;
    size_t sl = strlen(sub);
    while ((p = strstr(p, sub))) { n++; p += sl; }
    return n;
}
int pyc_str_isdigit(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isdigit((unsigned char)*s)) return 0;
    return 1;
}
int pyc_str_isalpha(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isalpha((unsigned char)*s)) return 0;
    return 1;
}
int pyc_str_isspace(const char* s) {
    if (!*s) return 0;
    for (; *s; s++) if (!isspace((unsigned char)*s)) return 0;
    return 1;
}

/* int_to_str, float_to_str */
char* pyc_int_to_str(long long n) {
    char buf[64]; snprintf(buf, sizeof(buf), "%lld", n); return strdup(buf);
}
char* pyc_float_to_str(double n) {
    char buf[64]; snprintf(buf, sizeof(buf), "%g", n); return strdup(buf);
}
char* pyc_bool_to_str(int b) { return b ? strdup("True") : strdup("False"); }
long long pyc_str_to_int(const char* s) {
    char* end; long long v = strtoll(s, &end, 0);
    if (*end) { fprintf(stderr, "ValueError: invalid int literal '%s'\n", s); exit(1); }
    return v;
}
double pyc_str_to_float(const char* s) {
    char* end; double v = strtod(s, &end);
    if (*end) { fprintf(stderr, "ValueError: invalid float literal '%s'\n", s); exit(1); }
    return v;
}

/* print helpers */
void pyc_print_int(long long v)   { printf("%lld", v); }
void pyc_print_float(double v)    { printf("%g", v); }
void pyc_print_str(const char* v) { printf("%s", v); }
void pyc_print_bool(int v)        { printf("%s", v ? "True" : "False"); }
void pyc_println(void)            { printf("\n"); }

/* assert */
void pyc_assert(int cond, const char* msg) {
    if (!cond) { fprintf(stderr, "AssertionError: %s\n", msg ? msg : ""); exit(1); }
}

/* range (returns PycList of ints as void* cast) */
PycList* pyc_range(long long start, long long stop, long long step) {
    PycList* l = pyc_list_new();
    if (step == 0) { fprintf(stderr, "ValueError: range step cannot be zero\n"); exit(1); }
    if (step > 0) { for (long long i = start; i < stop; i += step) pyc_list_append(l, (void*)(intptr_t)i); }
    else          { for (long long i = start; i > stop; i += step) pyc_list_append(l, (void*)(intptr_t)i); }
    return l;
}

/* init */
void pyc_init(void) { srand((unsigned)time(NULL)); }
/* ── End Runtime ── */

typedef struct Point Point;
typedef struct Person Person;

struct Point {
    double x;
    double y;
};

struct Person {
    char* name;
    long long age;
};

char* greet(char* name);
long long add(long long a, long long b);
double hypotenuse(double a, double b);
long long factorial(long long n);
int is_even(long long n);
char* fizzbuzz(long long n);
int main(int argc, char** argv);

double hypotenuse(double a, double b) {
    return sqrt((double)((a * a) + (b * b)));
}

long long factorial(long long n) {
    if ((n <= 1LL)) {
        return 1LL;
    }
    return (n * factorial((n - 1LL)));
}

int is_even(long long n) {
    return ((n % 2LL) == 0LL);
}

char* fizzbuzz(long long n) {
    if (((n % 15LL) == 0LL)) {
        return "FizzBuzz";
    } else if (((n % 3LL) == 0LL)) {
        return "Fizz";
    } else if (((n % 5LL) == 0LL)) {
        return "Buzz";
    } else {
        return pyc_int_to_str(n);
    }
}

char* greet(char* name) {
    return ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Hello, %s!", name); strdup(_fs); });
}

long long add(long long a, long long b) {
    return (a + b);
}

int main(int argc, char** argv) {
    pyc_init();
    printf("%s", "═══════════════════════════════");
    printf("%s", "     PyC Language Demo");
    printf("%s", "═══════════════════════════════");
    long long x = 42LL;
    double pi = 3.14159;
    char* name = "PyC";
    int flag = PYC_TRUE;
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"x=%lld  pi=%g  name=%s  flag=%s", x, pi, name, (flag ? "True" : "False")); strdup(_fs); }));
    char* msg = "started";
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"count=%lld  msg=%s", count, msg); strdup(_fs); }));
    long long result = add(10LL, 32LL);
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"add(10, 32) = %lld", result); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"5 ** 3 = %g", pow((double)(5LL), (double)(3LL))); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"17 // 5 = %lld", ((17LL) / (5LL))); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"hypotenuse(3, 4) = %g", hypotenuse(3.0, 4.0)); strdup(_fs); }));
    char* s = "  Hello, World!  ";
    printf("%s", pyc_str_strip(s));
    printf("%s", any_upper(pyc_str_strip(s)));
    printf("%s", any_lower(pyc_str_strip(s)));
    printf("%s", any_replace(pyc_str_strip(s), "World", "PyC"));
    printf("%s", pyc_str_startswith(s, "  "));
    printf("%s", pyc_str_contains(s, "World"));
    printf("%s", pyc_str_endswith(s, "  "));
    char* city = "Karachi";
    long long temp = 38LL;
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Weather in %s: %lld degrees", city, temp); strdup(_fs); }));
    PycList* nums = ({ PycList* _pyc_lit_8423 = pyc_list_new(); pyc_list_append(_pyc_lit_8423, (void*)(intptr_t)(10LL)); pyc_list_append(_pyc_lit_8423, (void*)(intptr_t)(20LL)); pyc_list_append(_pyc_lit_8423, (void*)(intptr_t)(30LL)); pyc_list_append(_pyc_lit_8423, (void*)(intptr_t)(40LL)); pyc_list_append(_pyc_lit_8423, (void*)(intptr_t)(50LL)); _pyc_lit_8423; });
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"List: len=%lld", pyc_list_len(nums)); strdup(_fs); }));
    pyc_list_append(nums, (void*)(intptr_t)(60LL));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"After append: len=%lld", pyc_list_len(nums)); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"nums[0]=%lld  nums[-1 + len(nums)]=?", ((long long)(intptr_t)pyc_list_get(nums, 0LL))); strdup(_fs); }));
    printf("%s", "Squares 1-5:");
    for (long long i = 1LL; i < 6LL; i += 1) {
        long long sq = (i * i);
        printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"  %lld^2 = %lld", i, sq); strdup(_fs); }));
    }
    long long total = 0LL;
    PycList* _pyc_list_n = nums;
    for (long long _pyc_i_n = 0; _pyc_i_n < pyc_list_len(_pyc_list_n); _pyc_i_n++) {
        void* n = pyc_list_get(_pyc_list_n, _pyc_i_n);
        total += n;
    }
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Sum of list = %lld", total); strdup(_fs); }));
    long long n = 1LL;
    printf("%s", "Powers of 2:");
    while ((n <= 32LL)) {
        printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"  %lld", n); strdup(_fs); }));
        n = (n * 2LL);
    }
    long long score = 75LL;
    if ((score >= 90LL)) {
        char* grade = "A";
    } else if ((score >= 80LL)) {
        grade = "B";
    } else if ((score >= 70LL)) {
        grade = "C";
    } else {
        grade = "F";
    }
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Score %lld => grade %s", score, grade); strdup(_fs); }));
    char* parity = (is_even(42LL) ? "even" : "odd");
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"42 is %s", parity); strdup(_fs); }));
    Point* p = ({ Point* _new_Point_126 = (Point*)malloc(sizeof(Point)); _new_Point_126->x = 3.0; _new_Point_126->y = 4.0; _new_Point_126; });
    double dist = hypotenuse(p->x, p->y);
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Point(%g, %g) distance = %g", p->x, p->y, dist); strdup(_fs); }));
    Person* person = ({ Person* _new_Person_130 = (Person*)malloc(sizeof(Person)); _new_Person_130->name = "Alice"; _new_Person_130->age = 30LL; _new_Person_130; });
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"Person: %s, age %lld", person->name, person->age); strdup(_fs); }));
    char* num_str = "42";
    long long num_int = pyc_str_to_int(num_str);
    double num_float = pyc_str_to_float("3.14");
    char* back_to_str = pyc_int_to_str(num_int);
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"int('42')=%lld  float('3.14')=%g  str(42)=%s", num_int, num_float, back_to_str); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"abs(-7) = %g", llabs((-7LL))); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"max(3,9) = %g", ((3LL) > (9LL) ? (3LL) : (9LL))); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"min(3,9) = %g", ((3LL) < (9LL) ? (3LL) : (9LL))); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"sqrt(144.0) = %g", sqrt((double)144.0)); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"floor(3.7) = %lld", (long long)floor(3.7)); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"ceil(3.2) = %lld", (long long)ceil(3.2)); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"factorial(10) = %lld", factorial(10LL)); strdup(_fs); }));
    printf("%s", "FizzBuzz 1-20:");
    for (long long i = 1LL; i < 21LL; i += 1) {
        printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"  %s", fizzbuzz(i)); strdup(_fs); }));
    }
    char* msg2 = greet("World");
    printf("%s", msg2);
    char* sentence = "the quick brown fox";
    void* words = pyc_str_split(sentence, " ");
    void* joined = pyc_str_join(words, " | ");
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"joined: %s", joined); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"ord('A') = %lld", ((long long)(unsigned char)("A")[0])); strdup(_fs); }));
    printf("%s", ({ char _fs[4096]; snprintf(_fs,sizeof(_fs),"chr(65) = %s", (char[]){(char)(65LL), 0}); strdup(_fs); }));
    printf("%s", "═══════════════════════════════");
    printf("%s", "         All done!");
    printf("%s", "═══════════════════════════════");
    return;
}

